### ISSUE TITLE
brew 无法安装，显示待下载版本1.3.0，而github显示最新版是1.2.2

### ISSUE THREAD

**Issue by lewisliuyi** [laishulu/macism#1]
brew显示的信息如下

==> Downloading https://github.com/laishulu/macism/archive/v1.3.0.tar.gz
==> Downloading from https://codeload.github.com/laishulu/macism/tar.gz/v1.3.0
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "macism"
Download failed: https://github.com/laishulu/macism/archive/v1.3.0.tar.gz

**Comment by laishulu** [comment]
已修正。

**Comment by lewisliuyi** [comment]
非常感谢您的工作（我之前通过修改brew中的macism的版本和sha256暂时能用了）

**Comment by lewisliuyi** [comment]
您可能还需要更新一下brew中的sha256值

**Comment by laishulu** [comment]
不用更新，原来就是对的，后来某次push的时候，忘了push tag，所有就丢失了。
```
❯ brew reinstall macism
==> Downloading https://github.com/laishulu/macism/archive/v1.3.0.tar.gz
==> Downloading from https://codeload.github.com/laishulu/macism/tar.gz/v1.3.0
#=#=-#  #
==> Reinstalling laishulu/macism/macism
==> swiftc macism.swift
🍺  /usr/local/Cellar/macism/1.3.0: 4 files, 88.3KB, built in 3 seconds
```

应该是你那边手工改了sha256，所以不对。

**Comment by lewisliuyi** [comment]
是更新的问题，我更新了brew untap和tap，再install macism，问题就解决了。谢谢您的指点
