### ISSUE TITLE
Allow enabling com.apple.CharacterPaletteIM

### ISSUE THREAD

**Issue by siikamiika** [laishulu/macism#10]
Kind of a niche use case, the `Emoji & Symbols` can also be edited through the usual menu based keyboard shortcuts, but since Apple has made it so difficult to save settings in text form I use macism with skhd instead since I already need it for some CJK IMEs.

https://github.com/laishulu/macism/blob/71f705be22e7b4aaa756cf1a2944a57cf1d05565/macism.swift#L56-L61

Removing the `$0.category == TISInputSource.Category.keyboardInputSource` condition allows using `macism com.apple.CharacterPaletteIM`, otherwise I get an error

**Comment by siikamiika** [comment]
@laishulu the latest commit still fails with `Input source \(CommandLine.arguments[1]) does not exist!`. I'm OK if you don't want to support this kind of feature but just confirming that I do have a keyboard shortcut for "Select the previous input source":
<img width="661" alt="Screenshot 2023-01-19 at 17 27 37" src="https://user-images.githubusercontent.com/5602483/213482979-74b1d876-3884-4604-b818-f90427be518d.png">

Here's the content of `inputSourceList` before filtering by category:
```swift
        let inputSourceList = inputSourceNSArray as! [TISInputSource]
        inputSourceList.forEach { src in
            print("\(src.id)\n\(src.category)\n")
        }
```
```
com.apple.keylayout.US
TISCategoryKeyboardInputSource

com.apple.CharacterPaletteIM
TISCategoryPaletteInputSource

com.apple.PressAndHold
TISCategoryPaletteInputSource

com.apple.inputmethod.SCIM
TISCategoryKeyboardInputSource

com.apple.inputmethod.SCIM.ITABC
TISCategoryKeyboardInputSource

com.apple.inputmethod.Kotoeri.RomajiTyping.Japanese
TISCategoryKeyboardInputSource

com.apple.inputmethod.Kotoeri.RomajiTyping
TISCategoryKeyboardInputSource

com.apple.50onPaletteIM
TISCategoryPaletteInputSource
```

So all `TISCategoryPaletteInputSource` are filtered out.

**Comment by laishulu** [comment]
sorry, I unintentionally reverted the codes to fix this issue.
will commit in minutes.

**Comment by laishulu** [comment]
Please try the latest version.

**Comment by siikamiika** [comment]
Works, thank you 👍

**Comment by laishulu** [comment]
To fix imcompatibility with https://github.com/laishulu/macism/issues/10,
You should add an extra option `--noKeyboardOnly` to disable the filter.
see: https://github.com/laishulu/macism#usage
