### ISSUE TITLE
切换输入法为rime时会弹出【字符检视器】

### ISSUE THREAD

**Issue by nailuoGG** [laishulu/macism#11]
配置信息：

- macOS Ventura 13.2 
- macism  stable 1.3.2, HEAD

现象：

在执行 `macism im.rime.inputmethod.Squirrel.Rime` 时，能够正常切换输入法为Rime，**但是会弹出字符检视器**，而切换成英文输入法时不会弹出。

<img width="726" alt="图片" src="https://user-images.githubusercontent.com/4554827/215407067-bd05f8b3-2c81-45e0-9406-8c83b6106052.png">

影响：

会影响到正在进行的文本输入

**Comment by laishulu** [comment]
我这里不会复现，
不知道问题出在哪里。

你试一下1.3.1版本，
也可能在满足#10的时候，
新引入的问题。

**Comment by nailuoGG** [comment]
我下载了1.3.1 和 1.3.2  的源码并编译，发现1.3.1没有这个问题，但是1.3.2 会出现

**Comment by AchillesG** [comment]
同样出现了这个问题，用了最新的Rime，执行 `macism im.rime.inputmethod.Squirrel.Hans` 可以复现

**Comment by laishulu** [comment]
那我加一点配置吧，
同时兼容[#10](https://github.com/laishulu/macism/issues/10)和[#11](https://github.com/laishulu/macism/issues/11)

**Comment by laishulu** [comment]
请测试反馈1.3.3版

**Comment by AchillesG** [comment]
解决了，现在切换Rime不会切到Emoji了
