### ISSUE TITLE
May I ask the license?

### ISSUE THREAD

**Issue by jjangga0214** [laishulu/macism#12]
Hi!

Thanks for this very useful project!

I'd like to include a part of this code in another project, [zmk](https://github.com/zmkfirmware/zmk), related to [this issue](https://github.com/zmkfirmware/zmk/issues/1716).
(I am not a maintainer, and whether the future PR would be accepted is not determined yet, by the way.)

It's MIT license. 

So macism's license is important. 
For example, if it's GPL, ZMK cannot include macism's code. At least, ZMK should create a new project with corresponding license.
But if macism's license is MIT, then ZMK can include macism's code.

Therefore I wonder what license is macism's.  

Sincerely,

**Comment by laishulu** [comment]
license added.
