### ISSUE TITLE
macism 是我到现在为止见过最稳定的方案，只是英文与中文输入法切换的延迟问题如何解决呢？

### ISSUE THREAD

**Issue by HF706** [laishulu/macism#14]
您好。我在我的 Mac 上用不同的按键对应不同输入法，CapsLock 键对应 ABC 输入法、右 Command 键对应 Squirrel 输入法、右 Option 键对应 hallelujah 输入法，使用 Keyboard Maestro 以按键作为 trigger 运行命令  `macism SOME_INPUT_SOURCE_ID`，再也没有出现过之前的中文输入法输入英文的问题，但是这个方案还是存在一个问题，那就是延迟，如果输入法切换过快时，会出现按下按键切换中文时，输入法还没切换过来，请问如何减小延迟呢？

**Comment by laishulu** [comment]
有个参数可以控制延迟。
但是切换一定是有延迟的。这个没有办法。
延迟太短的话，切换就会不成功。

https://github.com/laishulu/macism#usage

**Comment by liulu1998** [comment]
同意，在尝试了多个方案后，`macism` 最稳定。
可以在切换后手动敲一个 `空格`，相当于在中英文之间加个 `空格`，可以避免延迟，而且文字更清晰。 @HF706
