### ISSUE TITLE
Is there a way this works on Windows?

### ISSUE THREAD

**Issue by namangoel993** [laishulu/macism#15]

**Comment by LuciusChen** [comment]
try im-select https://github.com/daipeihust/im-select

**Comment by ZYinMD** [comment]
You can use the native windows settings: search "Advanced keyboard settings" in start menu, then go to "Input language hot keys".
![image](https://github.com/laishulu/macism/assets/32368482/360e3b11-afd6-4ce1-9abb-8ead1c51b4f8)

---

Alternatively you can use an AutoHotkey script to call windows native APIs to make the switch, for instance:
```autohotkey

; use ctrl-h to switch to Chinese, ctrl-j to switch to English.

^h::
  zh := DllCall("LoadKeyboardLayout", "Str", "00000804", "Int", 1)
  PostMessage 0x50, 0, %zh%,, A
Return

^j::
  en := DllCall("LoadKeyboardLayout", "Str", "00000409", "Int", 1)
  PostMessage 0x50, 0, %en%,, A
Return
```
