### ISSUE TITLE
Cannot switch to com.apple.inputmethod.SCIM.ITABC

### ISSUE THREAD

**Issue by willbchang** [laishulu/macism#2]
- App: Terminal.app
- OS: MacOS Big Sur 11.2.2

```bash
➜  ~ macism  
com.apple.keylayout.ABC
➜  ~ macism # Switched to Chinese pinyin manually                                                       
com.apple.inputmethod.SCIM.ITABC
➜  ~ macism com.apple.keylayout.ABC # Works well when switching to English input method                               
➜  ~ macism                        
com.apple.keylayout.ABC
➜  ~ 
➜  ~ macism com.apple.inputmethod.SCIM.ITABC # Got an error when switching to Chinese Pinyin                   
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file macism/macism.swift, line 80
[1]    14931 illegal hardware instruction  macism com.apple.inputmethod.SCIM.ITABC
```

<img width="780" alt="Screen Shot 2021-03-05 at 23 26 14" src="https://user-images.githubusercontent.com/14329786/110136650-e6176e00-7e0a-11eb-842c-5a5e4c223003.png">

**Comment by laishulu** [comment]
![Shortcut](https://user-images.githubusercontent.com/1224321/110139501-0eed3280-7e0e-11eb-8396-64e6b0b18a07.jpg)
You should have enabled this shortcut

**Comment by willbchang** [comment]
I think I found where the error is.

>When macism simulates the triggering of the shortcut key...

https://github.com/laishulu/macism/blob/243129946f2de35f8cb6437f249875737ae2873b/macism.swift#L113

I did some searches and found that `60` in `symbolichotkeys` means `Ctrl + Space`. I've disabled it in `Keyboard -> Shortcuts -> Input Sources`, because I'm using it in Alfred.

<img width="780" alt="Screen Shot 2021-03-05 at 23 39 40" src="https://user-images.githubusercontent.com/14329786/110138322-d3059d80-7e0c-11eb-8749-591fe8745a42.png">

<img width="1292" alt="Screen Shot 2021-03-05 at 23 47 31" src="https://user-images.githubusercontent.com/14329786/110138668-2c6dcc80-7e0d-11eb-852d-fc16a402cb28.png">

After swapping the shortcut, it works well.

```bash
➜  ~ macism                                 
com.apple.keylayout.ABC
➜  ~ macism com.apple.inputmethod.SCIM.ITABC
➜  ~ 
```

It's kind of hardcode here. I'm wondering is there a better way to do it? Maybe the check <kbd>CapsLock</kbd> key too?

<img width="780" alt="Screen Shot 2021-03-05 at 23 39 45" src="https://user-images.githubusercontent.com/14329786/110139619-33e1a580-7e0e-11eb-922b-c20a395656cf.png">

**Comment by laishulu** [comment]
You can use any shortcut here, but you must have the shortcut enabled.

**Comment by laishulu** [comment]
So, you can use a never manually triggered shortcut.

**Comment by willbchang** [comment]
I see, thanks! Could it possible to use <kbd>CapsLock</kbd>? It's already there.

**Comment by laishulu** [comment]
No, it only read that shortcut entry.
