### ISSUE TITLE
如何在vscode VSCodeVim 中使用macism

### ISSUE THREAD

**Issue by 52funny** [laishulu/macism#3]
如何在vscode 中使用这个软件呢？
VSCodeVim 官方给的是im-select 这个软件的配置。
希望作者能给一个macism的配置

**Comment by laishulu** [comment]
都是调用命令行，
有啥区别。

你自己调用就行了

**Comment by 52funny** [comment]
我尝试了使用如下配置
```json
  "vim.autoSwitchInputMethod.enable": true,
  "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
  "vim.autoSwitchInputMethod.obtainIMCmd": "/opt/homebrew/bin/macism",
  "vim.autoSwitchInputMethod.switchIMCmd": "/opt/homebrew/bin/macism {im}",
```
但是每次按下esc就会弹出辅助功能
![iShot2021-03-09 10.20.40.png](https://i.loli.net/2021/03/09/xzXIai3VUb4vlOg.png)
但是我在系统里面已经给予权限了
![iShot2021-03-09 10.22.34.png](https://i.loli.net/2021/03/09/teKlbqyWTkrODjV.png)
请问这是什么问题？

**Comment by laishulu** [comment]
不清楚
另外：
授权之后，是需要关掉vs code，重新打开的。
你这么做了么？

实在不行的话
你可以把这个授权删掉
重启电脑

重新触发那个授权提醒，
再试试

**Comment by 52funny** [comment]
好的感谢
我尝试重启了一下电脑就好了
