### ISSUE TITLE
如何在vim中自动切换输入法？

### ISSUE THREAD

**Issue by liang-0131** [laishulu/macism#4]
在Mac终端下的neovim如何在在退出插入模式后自动将输入法切换为英文

**Comment by laishulu** [comment]
see this plugin

https://github.com/laishulu/vim-macos-ime

**Comment by jukrb0x** [comment]
autocmd 

我目前使用的是im-select
```vimscript
autocmd InsertLeave * :silent !/usr/local/bin/im-select com.apple.keylayout.US
```
当离开插入模式时，他会自动执行`!/usr/local/bin/im-select com.apple.keylayout.US` 将输入法切换成英文（我的英文输入是`com.apple.keylayout.US`，如果你使用macism也是同理，详见readme）

---

@laishulu Hi, I am a bit confused, what is the main difference between macism and im-select or other similar tools?

**Comment by laishulu** [comment]
@jukrb0x 

see readme https://github.com/laishulu/macism

**Comment by PegasusWang** [comment]
用 im-select 搭配插件 smartim 亲测好用。

https://github.com/ybian/smartim
