### ISSUE TITLE
不能识别搜狗输入法通过 shift 切换的中英文状态啊

### ISSUE THREAD

**Issue by GanZhiXiong** [laishulu/macism#6]
因为我只使用 [搜狗输入法 for Mac - 支持全拼、双拼、模糊输入、苹果输入、云输入](https://pinyin.sogou.com/mac/) 这一个输入法，在需要使用英文时，我使用 shift 来切换（搜狗支持通过配置 shift 切换中英文）。
但是 macism 不能获取搜狗中英文状态，搜狗输入法在中文或英文状态下 macism 获取的输入源都只有一个，即 `com.sogou.inputmethod.sogou.pinyin`。

能解决这个问题吗？应该还有很多人有这样的需求。期待能解决。

**Comment by GanZhiXiong** [comment]
或者有没有其他软件能识别搜狗输入法通过 shift 切换的中英文状态？

**Comment by laishulu** [comment]
这个就不知道了。
本工具不提供这个功能。

**Comment by laishulu** [comment]
最好的办法，是用系统的abc输入法输入英文，搜狗只用来输入中文。

可以用capslock 来切换，
或者自己配置Karabiner，用escape来切换。
见：

https://blog.kiliwalk.com/macos-capslock-switch-input-source/

**Comment by GanZhiXiong** [comment]
感谢你的回答。
其实是想解决 [ShowyEdge](https://showyedge.pqrs.org/) 不能识别搜狗输入法按 shift 切换中英文的问题（[There are some input methods that can be switched to English directly by pressing shift, but ShowyEdge cannot recognize them · Issue #24 · pqrs-org/ShowyEdge](https://github.com/pqrs-org/ShowyEdge/issues/24)）。

为了解决这个问题，于是我寻找能识别输入源的代码，但是都无法识别区分搜狗的中英文。

**Comment by laishulu** [comment]
我也是用的showyedge，
我用系统的abc输入法输入英文，搜狗只用来输入中文。
所以就不存在问题了。

**Comment by GanZhiXiong** [comment]
这样使用确实不存在这个问题了。

还是搜狗的根据应用自动切换英文来的便利，所以我只用这个一个输入法。
虽然有软件可以配置哪些程序用哪种输入法，但它们似乎都必须要要给每个应用都配置才行。

比如你在搜狗中配置vscode添加到英文状态 App 清单，而微信没有在此清单中，你打开 vscode 就切换到搜狗内置的英文状态，然后你切换到微信，微信就是默认的中文输入。
而那些配置输入法的软件，如果你只配置了vscode 为英文输入法，没有配置微信为中文输入法，当切换到微信时，输入法还是英文。也就是它不能配置默认输入法（目前我还没有找到有这样功能的免费软件）。

**Comment by GanZhiXiong** [comment]
你可以试试搜狗的状态 App 清单，尝试后，你可能会放弃系统的英文输入法。

**Comment by laishulu** [comment]
1. Karabiner可以配置app的输入法
2. 搜狗可以配置app的输入法
3. MacOS可以记住app的输入法
<img width="668" alt="图片" src="https://user-images.githubusercontent.com/1224321/146901896-acdeaddf-60db-4ef0-ae00-7186fb84ee1d.png">

**Comment by laishulu** [comment]
>而那些配置输入法的软件，如果你只配置了vscode 为英文输入法，没有配置微信为中文输入法，当切换到微信时，输入法还是英文。也就是它不能配置默认输入法（目前我还没有找到有这样功能的免费软件）。

karabiner灵活度那么高，可以自己定制逻辑，你想要啥都可以的。

**Comment by GanZhiXiong** [comment]
> 3\. MacOS可以记住app的输入法

才发现这个功能，这个很实用👍

但是好像 App 关闭的时候不会保存当前使用输入法，重新打开 App 后，输入法不会切换到上次使用的输入法吧。

**Comment by laishulu** [comment]
MacOS你只切换app，不关闭app就行了。
没必要关闭app啊。

**Comment by GanZhiXiong** [comment]
是的，macOS 很少重启。但是关闭 App 的场景还是比较多的。

“自动切换到文稿的输入法”这功能正强大，它可以记录同一个 App，不同文本框的输入法，比如微信的聊天输入框和搜索框。

**在要是能App 关闭后也记录输入法就好了，比如 IDE 使用英文输入法较多，如果当前使用输入法为搜狗，打开 IDE 后，输入法还是搜狗中文，就很烦躁了。**
