### ISSUE TITLE
切换输入法后，快速按下键盘，先按下的部分按键会使用上次使用的输入法

### ISSUE THREAD

**Issue by GanZhiXiong** [laishulu/macism#8]
我通过 KE 配置 Shift 来执行此命令。
- 英文输入法下，按下 shift 后，**快速**按下 `jjj`，会部分输出中文。
- 中文输入法下，按下 shift 后，**快速**按下 `jjj`，会部分输出英文。
而用 KE 配置 Shift 映射为系统切换输入法的按键，则不会有此问题。

KE 配置如下：
```json
    {
      "description": "shift 映射为切换输入法的快捷键",
      "manipulators": [
        {
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift"
            }
          ],
          "to_if_alone": [
            {
              "key_code": "spacebar",
              "modifiers": "control"
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "shift 映射为切换输入法的脚本",
      "manipulators": [
        {
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift"
            }
          ],
          "to_if_alone": [
            {
              "shell_command": "/bin/zsh /Users/ganzhixiong/.config/karabiner/assets/shell/input-source-switcher.sh"
            }
          ],
          "type": "basic"
        }
      ]
    }
```

**Comment by laishulu** [comment]
没必要吧。。。
karabiner自己带输入法切换功能，
不需要调用macism

所以，你用这种方式，
就不需要用macism。

**Comment by laishulu** [comment]
macism的原理
是模拟系统快捷键来切换输入法，
会有个延迟，
代码里面也能看到有delay的参数。

本身设计是为了vim/emacs下，
从insert模式切换到normal模式时，
自动切换到英文输入法用的，
那种场景是没问题的。

但你要高速切换，
不留响应时间，
希望切换0延迟，
那是不行的。

**Comment by GanZhiXiong** [comment]
> karabiner自己带输入法切换功能，
> 不需要调用macism

1. 通过 KE 将 shift 映射为切换输入法的快捷键。有一个不是很严重的问题，就是在 IDEA 中按两下 shift 不会触发 IDEA 的 Searched Everywhere。
我追求的可能比较完美😂。

2. karabiner自己带输入法切换功能，你是说不需要配置我面的 json 就可以实现吗？

**Comment by GanZhiXiong** [comment]
> macism的原理 是模拟系统快捷键来切换输入法， 会有个延迟， 代码里面也能看到有delay的参数。
> 
> 本身设计是为了vim/emacs下， 从insert模式切换到normal模式时， 自动切换到英文输入法用的， 那种场景是没问题的。
> 
> 但你要高速切换， 不留响应时间， 希望切换0延迟， 那是不行的。

我试过添加 uSECONDS 参数，将其设置为 0 或 50 还是有这个问题。
你的代码应该是对具体输入法进行切换有延迟，而如果改为只是调用上一个输入法应该是没有这个问题。

![image](https://user-images.githubusercontent.com/27394631/147061287-99170221-a64c-42af-a8df-17b68290aa9a.png)

**Comment by laishulu** [comment]
>karabiner自己带输入法切换功能，你是说不需要配置我面的 json 就可以实现吗？

需要配置json，但是不需要调用外部的script

**Comment by laishulu** [comment]
>就是在 IDEA 中按两下 shift 不会触发 IDEA 的 Searched Everywhere。

可以考虑重映射<kbd>左shift + 右shift</kbd>这个组合键。
karabiner可以的，我现在就这么映射的。

**Comment by GanZhiXiong** [comment]
好的，谢谢你提供方案
